sudo: required
services:
  - docker
language: bash
env:
  - BUILD_NO=$(date '+%Y%m%d-%H%M%S')
install:
  - ./travis-install.sh
script:
  - ./travis-build.sh
deploy:
  - ./travis-deploy.sh
branches:
  only:
    - master
  except:
    - /^v\d.*$/
