sudo: required

services:
  - docker

language: bash

env:
  - GITHUB_USER=amarkwalder
  - GITHUB_REPO=hexo-site-github-pages
  - BUILD_NO=$(date '+%Y%m%d-%H%M%S')

install:
  - ./build/travis.sh install

script:
  - ./build/travis.sh build

deploy:
  provider: script
  script: ./build/travis.sh deploy

branches:
  only:
    - master
  except:
    - /^v\d.*$/
