sudo: required

services:
  - docker

language: bash

env:
  - BUILD_NO=$(date '+%Y%m%d-%H%M%S')

install:
  - ./travis.sh install

script:
  - ./travis.sh build

deploy:
  provider: script
  script: ./travis.sh deploy

branches:
  only:
    - master
  except:
    - /^v\d.*$/
