FROM node:6.10.2-alpine

MAINTAINER André Markwalder <andre.markwalder@gmail.com>

RUN apk update && \
    apk upgrade && \
    apk add --no-cache bash git && \
    npm install hexo-cli -g

COPY build.sh /

CMD [ "/build.sh" ]
